# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20170822_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
