# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 11:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_contest_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
