# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_auto_20170915_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
