# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 10:35
from __future__ import unicode_literals

import branditnew.contests.models.contest
import branditnew.contests.models.entries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_auto_20170915_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=branditnew.contests.models.entries.user_directory_path),
        ),
        migrations.AlterField(
            model_name='contest',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=branditnew.contests.models.contest.user_directory_path),
        ),
        migrations.AlterField(
            model_name='contest',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=branditnew.contests.models.contest.user_directory_path),
        ),
        migrations.AlterField(
            model_name='contest',
            name='sketch',
            field=models.FileField(blank=True, null=True, upload_to=branditnew.contests.models.contest.user_directory_path),
        ),
    ]
