# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
