# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0018_auto_20170924_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_contest_cost', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('sealed_contest_cost', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('nda_contest_cost', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('private_contest_cost', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('boost_entry_cost', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('hidden_entry_cost', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('standard_entry_cost', models.DecimalField(decimal_places=2, max_digits=100000000)),
            ],
        ),
    ]
