# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0020_auto_20170924_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='boost_entry_cost',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='price',
            name='hidden_entry_cost',
        ),
        migrations.RemoveField(
            model_name='price',
            name='nda_contest_cost',
        ),
        migrations.RemoveField(
            model_name='price',
            name='private_contest_cost',
        ),
        migrations.RemoveField(
            model_name='price',
            name='sealed_contest_cost',
        ),
        migrations.RemoveField(
            model_name='price',
            name='standard_entry_cost',
        ),
        migrations.RemoveField(
            model_name='price',
            name='top_contest_cost',
        ),
        migrations.AddField(
            model_name='price',
            name='price_type',
            field=models.CharField(default='standard', max_length=100),
            preserve_default=False,
        ),
    ]
