# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 11:22
from __future__ import unicode_literals

import branditnew.contests.models.projects
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0023_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Category'),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=branditnew.contests.models.projects.project_directory_path),
        ),
    ]
