# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0024_auto_20170927_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='contest',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
