# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0027_auto_20171005_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='prize_lower_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
