# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0029_auto_20171006_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_touched',
            field=models.BooleanField(default=False),
        ),
    ]
