# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0030_project_is_touched'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_touched',
            field=models.BooleanField(default=False),
        ),
    ]
