# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0032_project_num_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='num_submissions',
            field=models.SmallIntegerField(default=0),
        ),
    ]
