# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0037_entry_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry_comment',
            old_name='contest_submission',
            new_name='contest_entry',
        ),
    ]
