# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0040_entry_comment_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_comment',
            name='is_touched',
            field=models.BooleanField(default=False),
        ),
    ]
