# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0042_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('changes', models.TextField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Template')),
            ],
        ),
    ]
