# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0045_template_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
