# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0047_template_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
