# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0048_template_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Template_Category'),
        ),
    ]
