# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0051_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contests.Transaction_Status'),
        ),
    ]
