# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0052_auto_20171031_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template_order',
            old_name='total_cost',
            new_name='cost',
        ),
    ]
