# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0053_auto_20171101_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_order',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
