# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0054_template_order_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_order',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
