# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0055_auto_20171101_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
