# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0057_item_print_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='print_order',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
