# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0059_print_order_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='print_order',
            old_name='total_cost',
            new_name='cost',
        ),
    ]
