# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0060_auto_20171110_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='print_order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
