# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0062_auto_20171117_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
