# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0063_bid_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
