# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0064_transaction_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='payment_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='payment_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='print_order',
            name='payment_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
