# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0065_auto_20171121_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print_order',
            name='payment_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
