# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0067_points_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='points_purchase',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
