# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0068_points_purchase_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_amount', models.PositiveSmallIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('brandlancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modes_of_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='mode_of_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Modes_of_Payment'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='winning_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Entry'),
        ),
    ]
