# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0069_auto_20171124_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='mode_of_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Modes_of_Payment'),
        ),
    ]
