# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0070_auto_20171124_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='payment_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
