# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0072_achievement_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='payment_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
