# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0074_profile_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_details', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('brandlancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mode_of_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.Modes_of_Payment')),
            ],
        ),
    ]
