# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0075_payment_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_request',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
