# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0076_auto_20171127_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request',
            name='is_touched',
            field=models.BooleanField(default=False),
        ),
    ]
